name: Lab 1 task
description: Track work for a specific lab task
title: "[Task] <create an issue>"
labels: ["task"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: we are trying to get familiar with github
      placeholder: "Make X work with Y ..."
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Plan
      description: Steps you plan to take (update as you go).
      placeholder: |
        - [ ] Step 1
        - [ ] Step 2
        ...
    validations:
      required: true
